services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - task-manager-network
  mongodb:
    image: mongo:6-jammy
    ports:
      - "27017:27017"
    volumes:
      - ~/.docker-conf/mongodb/data/:/data/mongodb
    networks:
      - task-manager-network
  producer:
    build:
      context: .
      dockerfile: cmd/producer/Dockerfile
    container_name: producer
    depends_on:
      - rabbitmq
      - mongodb
    ports:
      - "8080:8080"
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      MONGODB_URL: mongodb://mongodb:27017
      API_PORT: 8080
    networks:
      - task-manager-network
  consumer:
    build:
      context: .
      dockerfile: cmd/consumer/Dockerfile
    container_name: consumer
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      MONGODB_URL: mongodb://mongodb:27017
    networks:
      - task-manager-network
networks:
  task-manager-network:
    driver: bridge
