FROM golang:1.21 AS builder

WORKDIR /app

COPY ../../go.mod ../../go.sum ./

RUN go mod download

COPY ../../cmd/consumer ./cmd/consumer
COPY ../../pkg ./pkg

RUN go build -o consumer ./cmd/consumer/main.go

FROM debian:bullseye-slim

WORKDIR /root/

COPY --from=builder /app/consumer .

CMD ["./consumer"]
