FROM golang:1.23.3 AS builder

WORKDIR /app

COPY ../../go.mod ../../go.sum ./

RUN go mod download

COPY ../../cmd/consumer .
COPY ../../pkg ./pkg

RUN go build -o consumer .

FROM ubuntu:22.04

WORKDIR /root/

COPY --from=builder /app/consumer .

CMD ["./consumer"]
