FROM golang:1.21 AS builder

WORKDIR /app

RUN go install github.com/swaggo/swag/cmd/swag@latest

COPY ../../go.mod ../../go.sum ./

RUN go mod download

COPY ../../cmd/producer ./cmd/producer
COPY ../../pkg ./pkg

RUN swag init --parseDependency --parseInternal --output ./docs

RUN go build -o producer ./cmd/producer/main.go

FROM debian:bullseye-slim

WORKDIR /root/

COPY --from=builder /app/producer .
COPY --from=builder /app/cmd/producer/docs ./docs

EXPOSE 8080

CMD ["./producer"]
