FROM golang:1.23.3 AS builder

WORKDIR /app

COPY ../../go.mod ../../go.sum ./

RUN go mod download

COPY ../../cmd/producer .
COPY ../../pkg ./pkg

RUN go build -o producer .

FROM ubuntu:22.04

WORKDIR /root/

COPY --from=builder /app/producer .
COPY ../../cmd/producer/docs ./docs

EXPOSE 8080

CMD ["./producer"]
