basePath: /
definitions:
  task.Task:
    description: Represents a task with ID, type, and payload information.
    properties:
      id:
        description: |-
          @ID Task ID
          @example 1
        type: integer
      payload:
        description: |-
          @Payload The actual task payload
          @example "Send welcome email"
        type: string
      type:
        description: |-
          @Type Type of the task
          @example "email"
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for creating tasks and sending them to RabbitMQ.
  title: Task Processor API
  version: "1.0"
paths:
  /tasks:
    post:
      consumes:
      - application/json
      description: Create a new task and send it to the RabbitMQ queue.
      parameters:
      - description: Task
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/task.Task'
      produces:
      - application/json
      responses:
        "201":
          description: Task created successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid request
          schema:
            additionalProperties: true
            type: object
      summary: Create a new task
swagger: "2.0"
